<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; }
  body { margin: 0; padding: 20px; background: #fff; color: #333; }
  .report-meta { margin-bottom: 20px; font-size: 11px; color: #666; }
  .section-title { font-size: 14px; font-weight: bold; color: #13400C; border-bottom: 1px solid #13400C; padding-bottom: 5px; margin: 20px 0 10px; }
  table.data-table { width: 100%; border-collapse: collapse; table-layout: fixed; }
  table.data-table th, table.data-table td { padding: 6px 8px; font-size: 11px; text-align: left; }
  table.data-table th { background: #13400C; color: #fff; }
  table.data-table td { border-bottom: 1px solid #e0e0e0; }
  table.data-table tr:nth-child(even) td { background: #fafafa; }
  .footer { margin-top: 30px; border-top: 1px solid #e0e0e0; padding-top: 10px; font-size: 10px; color: #999; text-align: center; }
</style>
</head>
<body>

  <div style="font-size: 18px; font-weight: bold; color: #13400C; margin-bottom: 5px;">
    {{ config('app.name') }}
  </div>
  <div style="font-size: 12px; color: #666; margin-bottom: 15px;">
    Members List
  </div>
  <hr style="border: none; border-top: 2px solid #13400C; margin-bottom: 15px;">

  <div class="report-meta">
    Generated on: {{ now()->format('M d, Y h:i A') }} &nbsp;|&nbsp;
    Generated by: {{ auth()->user()->name }}
  </div>

  <div class="section-title">Member Names</div>
  <table class="data-table">
    <thead>
      <tr>
        <th style="width: 8%;">#</th>
        <th style="width: 92%;">Name</th>
      </tr>
    </thead>
    <tbody>
      @forelse($members as $index => $name)
        <tr>
          <td>{{ $index + 1 }}</td>
          <td>{{ $name }}</td>
        </tr>
      @empty
        <tr>
          <td colspan="2" style="text-align: center; color: #999;">No members found</td>
        </tr>
      @endforelse
    </tbody>
  </table>

  <div class="footer">
    {{ config('app.name') }} &mdash; Confidential &mdash; Generated {{ now()->format('M d, Y') }}
  </div>

</body>
</html>
