<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { font-family: 'Space Grotesk', sans-serif;
      font-size: 12px; }
  body { margin: 0; padding: 20px;
         background: #fff; color: #333; }

  .report-meta { margin-bottom: 20px;
                 font-size: 11px; color: #666; }

  .section-title { font-size: 13px;
                   font-weight: bold;
                   color: #13400C;
                   border-bottom: 1px solid #13400C;
                   padding-bottom: 5px;
                   margin: 20px 0 10px; }

  table.data-table { width: 100%;
                     border-collapse: collapse;
                     margin-bottom: 20px;
                     table-layout: fixed;
                     word-wrap: break-word; }
  table.data-table th,
  table.data-table td { word-wrap: break-word;
                        overflow-wrap: break-word;
                        padding: 6px 5px;
                        font-size: 10px; }
  table.data-table th { background: #13400C;
                        color: #F2EBC4;
                        text-align: left; }
  table.data-table td { border-bottom: 1px solid #f0f0f0; }
  table.data-table tr:nth-child(even) td {
    background: #fafafa; }

  .footer { margin-top: 30px;
            border-top: 1px solid #e0e0e0;
            padding-top: 10px;
            font-size: 10px; color: #999;
            text-align: center; }
</style>
</head>
<body>

  <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
    <tr>
      <td style="width: 70px; vertical-align: middle;">
        <img src="{{ public_path('assets/logo_full.jpeg') }}" alt="MDIA"
             style="width: 60px; height: 60px; object-fit: cover; border-radius: 6px;">
      </td>
      <td style="vertical-align: middle; padding-left: 12px;">
        <div style="font-size: 18px; font-weight: bold; color: #13400C; margin: 0;">
          {{ config('app.name') }}
        </div>
        <div style="font-size: 11px; color: #666; margin-top: 3px;">
          Members List
        </div>
      </td>
    </tr>
  </table>
  <hr style="border: none; border-top: 2px solid #13400C; margin-bottom: 15px;">

  <div class="report-meta">
    Generated on: {{ now()->format('M d, Y h:i A') }} &nbsp;|&nbsp;
    Generated by: {{ auth()->user()->name }}
  </div>

  <div class="section-title">Members</div>
  <table class="data-table">
    <thead>
      <tr>
        <th style="width: 4%;">#</th>
        <th style="width: 22%;">Name</th>
        <th style="width: 18%;">Country</th>
        <th style="width: 14%;">Phone</th>
        <th style="width: 28%;">Email</th>
        <th style="width: 14%;">Reg. Year</th>
      </tr>
    </thead>
    <tbody>
      @forelse($members as $index => $member)
        <tr>
          <td>{{ $index + 1 }}</td>
          <td>{{ $member->name }}</td>
          <td>{{ $member->country_of_residence ?? '—' }}</td>
          <td>{{ $member->phone ?? '—' }}</td>
          <td>{{ $member->email ?? '—' }}</td>
          <td>{{ $member->registration_year ?? '—' }}</td>
        </tr>
      @empty
        <tr>
          <td colspan="6" style="text-align: center; color: #999;">No members found</td>
        </tr>
      @endforelse
    </tbody>
  </table>

  <div class="footer">
    {{ config('app.name') }} &mdash;
    Confidential &mdash;
    Generated {{ now()->format('M d, Y') }}
  </div>

</body>
</html>
