<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { font-family: 'Space Grotesk', sans-serif;
      font-size: 12px; }
  body { margin: 0; padding: 20px;
         background: #fff; color: #333; }

  .report-meta { margin-bottom: 20px;
                 font-size: 11px; color: #666; }

  .summary-grid { width: 100%;
                  border-collapse: collapse;
                  margin-bottom: 20px;
                  table-layout: fixed; }
  .summary-grid td { width: 25%;
                     padding: 12px;
                     text-align: center;
                     border: 1px solid #e0e0e0;
                     word-wrap: break-word;
                     overflow-wrap: break-word; }
  .summary-label { font-size: 10px;
                   color: #666;
                   text-transform: uppercase;
                   letter-spacing: 0.05em; }
  .summary-value { font-size: 16px;
                   font-weight: bold;
                   color: #13400C;
                   margin-top: 4px; }

  .section-title { font-size: 13px;
                   font-weight: bold;
                   color: #13400C;
                   border-bottom: 1px solid #13400C;
                   padding-bottom: 5px;
                   margin: 20px 0 10px; }

  table.data-table { width: 100%;
                     border-collapse: collapse;
                     margin-bottom: 20px;
                     table-layout: fixed;
                     word-wrap: break-word; }
  table.data-table th,
  table.data-table td { word-wrap: break-word;
                        overflow-wrap: break-word;
                        padding: 6px 5px;
                        font-size: 10px; }
  table.data-table th { background: #13400C;
                        color: #F2EBC4;
                        text-align: left; }
  table.data-table td { border-bottom: 1px solid #f0f0f0; }
  table.data-table tr:nth-child(even) td {
    background: #fafafa; }

  .badge-verified { background: #d4edda;
                    color: #155724;
                    padding: 2px 6px;
                    border-radius: 3px;
                    font-size: 10px; }
  .badge-pending { background: #fff3cd;
                   color: #856404;
                   padding: 2px 6px;
                   border-radius: 3px;
                   font-size: 10px; }

  .footer { margin-top: 30px;
            border-top: 1px solid #e0e0e0;
            padding-top: 10px;
            font-size: 10px; color: #999;
            text-align: center; }

  .page-break { page-break-before: always; }
</style>
</head>
<body>

  <table style="width: 100%; border-collapse: collapse; margin-bottom: 15px;">
    <tr>
      <td style="width: 70px; vertical-align: middle;">
        <img src="{{ public_path('assets/logo_full.jpeg') }}" alt="MDIA"
             style="width: 60px; height: 60px; object-fit: cover; border-radius: 6px;">
      </td>
      <td style="vertical-align: middle; padding-left: 12px;">
        <div style="font-size: 18px; font-weight: bold; color: #13400C; margin: 0;">
          {{ config('app.name') }}
        </div>
        <div style="font-size: 11px; color: #666; margin-top: 3px;">
          Payment Report
        </div>
        @if(!empty($filters['year']))
          <div style="font-size: 10px; color: #666;">
            Year: {{ $filters['year'] }}
          </div>
        @endif
        @if(!empty($filters['from']) && !empty($filters['to']))
          <div style="font-size: 10px; color: #666;">
            Period: {{ $filters['from'] }} to {{ $filters['to'] }}
          </div>
        @endif
      </td>
    </tr>
  </table>
  <hr style="border: none; border-top: 2px solid #13400C; margin-bottom: 15px;">

  <div class="report-meta">
    Generated on: {{ now()->format('M d, Y h:i A') }} &nbsp;|&nbsp;
    Generated by: {{ auth()->user()->name }}
  </div>

  <div class="section-title">Summary</div>
  <table class="summary-grid">
    <tr>
      <td>
        <div class="summary-label">Total Collections</div>
        <div class="summary-value">
          ${{ number_format($summary['total_collections'], 2) }}
        </div>
      </td>
      <td>
        <div class="summary-label">Total Verified</div>
        <div class="summary-value">
          ${{ number_format($summary['total_verified'], 2) }}
        </div>
      </td>
      <td>
        <div class="summary-label">Total Pending</div>
        <div class="summary-value">
          ${{ number_format($summary['total_pending'], 2) }}
        </div>
      </td>
      <td>
        <div class="summary-label">Total Payments</div>
        <div class="summary-value">
          {{ $summary['total_payments'] }}
        </div>
      </td>
    </tr>
  </table>

  <div class="section-title">Breakdown by Payment Type</div>
  <table class="data-table">
    <thead>
      <tr>
        <th style="width: 40%;">Payment Type</th>
        <th style="width: 20%;">Verified Total</th>
        <th style="width: 20%;">Pending Total</th>
        <th style="width: 20%;">Count</th>
      </tr>
    </thead>
    <tbody>
      @forelse($breakdown as $item)
        <tr>
          <td>{{ $item['name'] }}</td>
          <td>${{ number_format($item['verified_total'], 2) }}</td>
          <td>${{ number_format($item['pending_total'], 2) }}</td>
          <td>{{ $item['count'] }}</td>
        </tr>
      @empty
        <tr>
          <td colspan="4" style="text-align:center;
              color:#999;">No data found</td>
        </tr>
      @endforelse
    </tbody>
  </table>

  <div class="section-title page-break">Payment Records</div>
  <table class="data-table">
    <thead>
      <tr>
        <th style="width: 4%;">#</th>
        <th style="width: 16%;">Member</th>
        <th style="width: 14%;">Payment Type</th>
        <th style="width: 10%;">Amount</th>
        <th style="width: 7%;">Year</th>
        <th style="width: 10%;">Status</th>
        <th style="width: 13%;">Payment Date</th>
        <th style="width: 16%;">Verified By</th>
        <th style="width: 10%;">Notes</th>
      </tr>
    </thead>
    <tbody>
      @forelse($payments as $index => $payment)
        <tr>
          <td>{{ $index + 1 }}</td>
          <td>{{ $payment['member_name'] }}</td>
          <td>{{ $payment['payment_type_name'] }}</td>
          <td>${{ number_format($payment['amount'], 2) }}</td>
          <td>{{ $payment['year'] }}</td>
          <td>
            @if($payment['status'] === 'verified')
              <span class="badge-verified">Verified</span>
            @else
              <span class="badge-pending">Pending</span>
            @endif
          </td>
          <td>{{ $payment['payment_date'] }}</td>
          <td>{{ $payment['status'] === 'verified' ? ($payment['verified_by_name'] ?? 'N/A') : '-' }}</td>
          <td>{{ $payment['notes'] ?? '-' }}</td>
        </tr>
      @empty
        <tr>
          <td colspan="9" style="text-align:center; color:#999;">No payments found</td>
        </tr>
      @endforelse
    </tbody>
  </table>

  <div class="footer">
    {{ config('app.name') }} &mdash;
    Confidential &mdash;
    Generated {{ now()->format('M d, Y') }}
  </div>

</body>
</html>
